import time
print("_____Text Analyzer_____")
print()
time.sleep(0.75)
print()
text=input("Enter a Word or Sentence :- ")
print()
if len(text) < 3:
    time.sleep(0.5)
    print("❌ Can't be less than 3 characters") 
    print()
    print("Relaunch the program")
else:
    
    print("Analyzing...")
    time.sleep(2)
    print()
    print("First letter :- ",text[0])
    time.sleep(0.25)
    print()
    print("Last letter :- ",text[-1])
    time.sleep(0.25)
    print()
    print("Third letter :- ",text[2])
    time.sleep(0.25)
    print()
    print("Last third letter :- ",text[-2])
    time.sleep(0.25)
    print()
    print("Total character : ",len(text))
    time.sleep(0.25)
    print()
    print()
    print("Character one by one :")
    time.sleep(0.5)
    print()
    for c in text:
        print(c)
    print()
    time.sleep(0.25)
    if len(text) > 5:    
        print("Character position :-")
        print()
        print("0 : ",text[0])
        print("1 : ",text[1])
        print("2 : ",text[2])
        print("3 : ",text[3])
        print("4 : ",text[4])
        print("5 : ",text[5])
        print()
    else:
        print("Length of character is less than 5, So character position can't be determined.")   
time.sleep(0.25)
print()
print("--------------------------Thank you--------------------------")
print()    